name: kimurapinn
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - pyyaml
  - matplotlib
  - pytest
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pip

