#!/usr/bin/env python3
"""
Script: 06_simulate_single_pop_sfs.py

Purpose:
    Simulate independent single-population SNVs under a configurable
    Wright-Fisher approximation and save a count-indexed folded SFS.

Biological Question:
    What folded SFS is generated by a known time-varying selection trajectory in
    a single population?

Assumptions:
    - Folded SFS is used because ancestral allele is unavailable.
    - Simulated records represent SNVs.
    - Allele counts are sampled from a Wright-Fisher binomial process.

Input:
    - YAML simulation config specifying n_pop, n_variants, gamma(t), demography,
      and initial allele frequencies.

Output:
    - simulated_variants.tsv
    - folded_sfs_simulated.tsv
    - true_gamma_trajectory.tsv
    - simulation_config.yaml
    - metrics.json

Process Schematic:
    Simulation config
        -> draw initial allele frequencies
        -> simulate Wright-Fisher trajectories
        -> sample final allele counts
        -> fold segregating variants by allele count
        -> save variants, SFS, gamma, and metrics

Example:
    python scripts/06_simulate_single_pop_sfs.py \
        --config configs/simulate_time_varying_selection.yaml \
        --output-dir results/simulation_step_gamma_test
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.simulation.simulate_sfs import simulate_single_population_sfs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Simulate a single-population folded SFS.")
    parser.add_argument("--config", required=True, help="Simulation YAML config.")
    parser.add_argument("--output-dir", required=True, help="Output directory.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    with Path(args.config).open("r") as handle:
        config = yaml.safe_load(handle) or {}
    summary = simulate_single_population_sfs(config, args.output_dir)
    print(f"Simulated SFS: {summary['folded_sfs']}")


if __name__ == "__main__":
    main()
